<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateListingsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('listings', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id');
            $table->integer('cat_id');
            $table->integer('sub_cat_id');
            $table->integer('location_id');
            $table->integer('featured_listing');
            $table->string('title', 255);
            $table->string('listing_slug', 255);
            $table->longText('description');
            $table->text('video');
            $table->text('address');
            $table->string('map_lat', 255);
            $table->string('map_long', 255);
            $table->text('amenities');
            $table->string('working_hours_mon', 255);
            $table->string('working_hours_tue', 255);
            $table->string('working_hours_wed', 255);
            $table->string('working_hours_thurs', 255);
            $table->string('working_hours_fri', 255);
            $table->string('working_hours_sat', 255);
            $table->string('working_hours_sun', 255);
            $table->string('featured_image', 255);
            $table->string('review_avg', 255);
            $table->integer('status');
            $table->nullableTimestamps();
            $table->text('keywords');
            $table->bigInteger('consultation_fee');
            $table->bigInteger('contact');

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('listings');
    }
}
