<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('login_with', 255);
            $table->string('usertype', 20)->nullable();
            $table->string('first_name', 255);
            $table->string('last_name', 255);
            $table->string('email', 255);
            $table->string('password', 60);
            $table->string('gender', 20);
            $table->string('image_icon', 255)->nullable();
            $table->string('mobile', 255);
            $table->string('contact_email', 255);
            $table->string('website', 255);
            $table->text('address');
            $table->string('facebook_url', 255);
            $table->string('twitter_url', 255);
            $table->string('linkedin_url', 255);
            $table->string('dribbble_url', 255);
            $table->string('instagram_url', 255);
            $table->string('facebook_id', 255);
            $table->string('google_id', 255);
            $table->rememberToken();
            $table->nullableTimestamps();
            $table->text('membership')->nullable();
            $table->text('service_1');
            $table->bigInteger('consultation_fee');
            $table->integer('referral');
            $table->integer('refers');
            $table->integer('patient');
            $table->unique('email', 'users_email_unique');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
