<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSettingsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('settings', function (Blueprint $table) {
            $table->increments('id');
            $table->string('site_name', 255);
            $table->string('site_email', 255);
            $table->string('site_logo', 255);
            $table->string('site_favicon', 255);
            $table->string('site_description', 255);
            $table->string('google_map_api', 255);
            $table->text('site_header_code');
            $table->text('site_footer_code');
            $table->string('site_copyright', 255);
            $table->text('addthis_share_code');
            $table->text('disqus_comment_code');
            $table->text('facebook_comment_code');
            $table->string('home_slide_image1', 255);
            $table->string('home_slide_image2', 255);
            $table->string('home_slide_image3', 255);
            $table->string('home_slide_title', 255);
            $table->text('home_slide_text');
            $table->string('page_bg_image', 255);
            $table->string('about_title', 255);
            $table->longText('about_description');
            $table->string('contact_title', 255);
            $table->text('contact_address');
            $table->string('contact_email', 255);
            $table->string('contact_number', 255);
            $table->string('contact_lat', 255);
            $table->string('contact_long', 255);
            $table->string('terms_of_title', 255);
            $table->longText('terms_of_description');
            $table->string('privacy_policy_title', 255);
            $table->longText('privacy_policy_description');
            $table->string('facebook_url', 255);
            $table->string('twitter_url', 255);
            $table->string('gplus_url', 255);
            $table->string('linkedin_url', 255);

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('settings');
    }
}
